### ISSUE TITLE
Data Missing

### ISSUE THREAD

**Issue by besandrew** [BoltAI/BoltAI#1]
Getting a message Data could not be read because it is missing - all API keys Green

**Comment by simonwj** [comment]
Hi Daniel, I'm getting that message as well in the chat UI. "The data couldn't be read because it is missing." What I have just discovered is that I am trying to use GPT-4 and yet I have not been accepted to join the beta programme for API access.  I think this is my problem.  I do not get the message if I am using GPT-3.

**Comment by longseespace** [comment]
You're right @simonwj. I checked and looks like this error happen when we're trying to access the resources that are not available to us.

I will show a more user friendly error message.

Thanks

**Comment by longseespace** [comment]
I've fixed this in the latest version (BoltAI v1.7 build 21).

Related PR: https://github.com/MacPaw/OpenAI/pull/87

**Comment by simonwj** [comment]
@longseespace Interesting to note that OpenAI made GPT-4 API available to all paying customers yesterday [GPT 4 API general availability](https://openai.com/blog/gpt-4-api-general-availability)
