### ISSUE TITLE
Can't worrk with pictures exported from PDF anymore

### ISSUE THREAD

**Issue by Lderib** [BoltAI/BoltAI#126]
Hello,

A few days ago, I successfully exported a 100-page PDF contract as JPEG images, uploaded them to BOLT, and used ChatGPT-4o to extract a list of elements. Everything worked perfectly.

However, since yesterday, I’ve been unable to perform similar tasks with the images. The process runs for a while, displaying the message "Assistant is thinking...", but then it returns an empty line. Additionally, all the images disappear.

It seems that BOLT is currently unable to upload the images to ChatGPT-4o.

I've included some printscreen.

Thank you,
Luc

![CleanShot 2024-07-10 at 20 29 18@2x](https://github.com/BoltAI/BoltAI/assets/33206049/a89c26c0-91d6-47dc-9b9c-a81657f420f3)
![CleanShot 2024-07-10 at 20 29 46@2x](https://github.com/BoltAI/BoltAI/assets/33206049/fb17f6bf-fedc-42e7-b8c6-6b426cb8240d)
![CleanShot 2024-07-10 at 20 30 05@2x](https://github.com/BoltAI/BoltAI/assets/33206049/9b3538b8-70ea-4eb5-93d3-fed41e6398d2)

**Comment by longseespace** [comment]
Thanks for the report. My best guess is that you've ran out of AI credits, or you've reached the model's context limit.

Any chance you can share the images with me so I could investigate further. My email address: daniel@boltai.com

Also, if possible try these 2:

- Switch to your API key instead of using Setapp AI service. This is to check if you've ran out of credits / reached Setapp's sepcific context limit
- Use just a few images. This is to check if your input is too large (beyond the model's context limit)

**Comment by longseespace** [comment]
Hi @Lderib. I've added the ability to attach PDF and other documents directly to a chat. So you no longer need to take screenshots. Can you update to the latest version and give it a try. 

Here is the guide: https://boltai.com/docs/chat-ui/document-analysis
