### ISSUE TITLE
Cost estimate not displayed for ChatGPT-4o model (works for GPT-4o Mini)

### ISSUE THREAD

**Issue by ionescu77** [BoltAI/BoltAI#169]
**Describe the bug**
In the title bar on the second line there is the Model chosen and also a cost estimation (for API costs).
This cost estimation works for the `GPT-4o Mini`, but today I have chosen another Model `ChatGPT-4o` and I have no cost estimate.

**To Reproduce**
1. Go to 'Start New Chat'
2. Click on 'Model Selection Dropdown'
3. Scroll down to 'ChatGPT-4o' and select
4. Enter a prompt

**Expected behavior**
After the response the cost/usage should be displayed in the title bar (for ex.: `~$0.011158`)

**Screenshots**

![image](https://github.com/user-attachments/assets/227d0e6d-fa82-4fa9-9063-ac4daa05bdf5)

![image](https://github.com/user-attachments/assets/50b2212a-fd60-4074-97c6-5ec7b13ed921)

**Version (please complete the following information):**
 - macOS: 14.6.1 - Sonoma
 - app version v1.21.1
 - [ ] Setapp Version?
> What is this? ⤴️

**Additional context**

<img width="292" alt="Screenshot 2024-09-20 at 16 40 16" src="https://github.com/user-attachments/assets/455f948a-393c-4ccb-abc8-1eaccb4a69aa">

I would like to ask why are there both a
```
ChatGPT-4o
```
and
```
GPT-4o
```
models in the dropdown?

Thank you!

**Comment by longseespace** [comment]
This is expected. The `ChatGPT-4o` model is **different** from the `GPT-4o` model. And currently I still haven't found the official pricing for this model. That's why you don't see the cost estimate. Please let me know if you found its pricing details.

ChatGPT-4o is the model that the official ChatGPT app uses. It doesn't support advanced features such as tool use and so on.

GPT-4o is intended to use in production. It supports advanced API features such as tool use etc.

Reference: https://platform.openai.com/docs/models/gpt-4o

![CleanShot 2024-09-21 at 15 17 01@2x](https://github.com/user-attachments/assets/908609fd-f2b1-460a-abf2-217744fc1be3)
