### ISSUE TITLE
tool_use error

### ISSUE THREAD

**Issue by jlpajares** [BoltAI/BoltAI#170]
**Describe the bug**
Getting the error `status code 400Requests which include tool_use or tool_result blocks must define tools.` while chatting.

**To Reproduce**
1. Start new chat using Claude Sonnet (don't know if it happens with other models), having web search and web browsing plugins enabled.
2. Disable both plugins after a few messages.
3. Get the error.
The error does not show anymore if I re-enable the plugins.

**Version (please complete the following information):**
 - macOS 14.6.1
 - app v1.21.1 (build 108)
 - [ X] Setapp Version?

**Comment by longseespace** [comment]
Ah interesting edge case. When you disable the plugins, what is your expectation? 

A simple implementation is just ignore `tool_use` and `tool_result` when plugins are disabled but I will need to double check because Anthropic is very strict about chat message's order and other requirements regarding tool use content.

**Comment by jlpajares** [comment]
Me expectation was to just continue chatting without using those plugins. I realised that the conversation was getting too influenced by the web results and wanted the AI to focus on the core of the conversation.

**Comment by longseespace** [comment]
Fixed in v1.22.0: https://boltai.com/changelog
