### ISSUE TITLE
AI Commands only work with OpenAI API

### ISSUE THREAD

**Issue by amolenk** [BoltAI/BoltAI#34]
When trying to use AI Commands with only an **Azure** OpenAI model set up, I get the following error message:

`OpenAI API Key missing. Go to Setting and enter your API Key`

I expect BoltAI to use the Azure OpenAI model as I've set that as the default model.

**Comment by longseespace** [comment]
Ah my bad. Hey @amolenk, in the latest version, you can choose to use a custom AI Service Provider / AI model other than the default model. I will fix it so that it would fallback to the default service provider.

![CleanShot 2024-02-26 at 08 00 08@2x](https://github.com/BoltAI/BoltAI/assets/187720/7eccf474-3e8b-4653-8160-dfc539a40f9e)

**Comment by longseespace** [comment]
I've implemented the fallback in v1.14.1. Cheers.
