### ISSUE TITLE
Claude 3 API - Making 2 extra call with another model

### ISSUE THREAD

**Issue by pixexid** [BoltAI/BoltAI#57]
![0-3-2024_zeRaDboWLD](https://github.com/BoltAI/BoltAI/assets/54691335/6909b41c-9254-4da4-984b-2a57659acffb)
I chose the Haiku model, but your app is making 3 API calls for one message: twice for the Sonnet model and once for the Haiku model.

**Comment by longseespace** [comment]
Hey @pixexid. Thanks for the bug report. This happens because BoltAI ask for a relevant title for the chat. You can disable this feature in Settings. Though there is indeed a bug since it should use `haiku` for the title generation, not `sonnet`. I'm working on the fix right now.

I can't seem to replicate the additional sonnet http request though. Can you double check if it happens for a message in an already-existed chat (not new chat)

Meanwhile, you can disable the title generation feature here.

![CleanShot 2024-04-01 at 11 55 29@2x](https://github.com/BoltAI/BoltAI/assets/187720/9401a95b-2b0a-4f20-98cb-b593e96ef3f9)

**Comment by longseespace** [comment]
I've fixed this in v1.15.6, please update and confirm. Feel free to reopen this issue otherwise.
