### ISSUE TITLE
Bug: Web browsing/search not working

### ISSUE THREAD

**Issue by sammcj** [BoltAI/BoltAI#75]
I can't seem to get web browsing / search working in BoltAI.

- Search is enabled and configured.
- Browsing is enabled and configured.
- I've tried multiple models (llama-3 8b, 70b, Phi 3 mini, Command R etc...)

What happens:

- When providing a link and asking for information from the URL browsing doesn't seem to occur.
- When asking the LLM in chat to search the web, LLMs respond stating they don't have access the internet / their training data cut off date etc...

<img width="1207" alt="SCR-20240425-uban" src="https://github.com/BoltAI/BoltAI/assets/862951/add5bc22-5c95-4ece-bc7d-d56bab2b7e58">

**Comment by longseespace** [comment]
Sorry for the confusion. This is a bug in the UI. You should not be able to enable plugins when using Ollama. 

The reason is both these plugins require "Function Calling" capability and currently BoltAI only supports it for OpenAI / Azure / Anthropic.

I will add support for more services & models in the next version.

Keep in mind that the prerequisites is the LLM must support Function Calling.

**Comment by sammcj** [comment]
Oh I see, thanks for the clarification.

Looking forward to this arriving, it's certainly a feature I used in MindMac quite a bit before switching over.

**Comment by longseespace** [comment]
This has been fixed I think. Feel free to open otherwise.
